import sys

__author__ = 'PC-DD-10'

from urllib.parse import quote
from urllib.request import Request, urlopen, HTTPError
import json, csv, re, uuid
from settings import *

strFile = "data/tcga_dataset_resource.csv"

dict_orga = {}
dict_orga['name'] = 'TCGA'.lower()
dict_orga['title'] = 'The Cancer Genome Atlas'
dict_orga['description'] = "The Cancer Genome Atlas (TCGA) Data Portal provides a platform for researchers to search, download, and analyze data sets generated by TCGA. It contains clinical information, genomic characterization data, and high level sequence analysis of the tumor genomes. Please note some data on the TCGA Data Portal are in controlled-access. Please visit the Access Tiers page for more information."

request = Request('http://%s/api/action/organization_create' % ckan_host)
data_string = quote(json.dumps(dict_orga)).encode('utf8')
request.add_header('Authorization', ckan_api_key)
try:
    response = urlopen(request, data_string)
    # Use the json module to load CKAN's response into a dictionary.
    response_dict = json.loads(response.read().decode())
    assert response_dict['success'] is True
except HTTPError as error:
    print("{}: {}".format(dict_orga["name"], error.read()))



# sys.exit()

for row in csv.DictReader(open(strFile, encoding='utf-8'), delimiter=";"):

    dict_dataset = {}
    dict_dataset['owner_org'] = dict_orga['name']
    dict_dataset['name'] = re.sub(r'\W', '-', row['resource']).lower()
    dict_dataset['title'] = row['resource']


    request = Request('http://%s/api/action/package_create' % ckan_host)
    data_string = quote(json.dumps(dict_dataset)).encode('utf8')

    print(data_string)

    request.add_header('Authorization', ckan_api_key)
    try:
        response = urlopen(request, data_string)
        # Use the json module to load CKAN's response into a dictionary.
        response_dict = json.loads(response.read().decode())
        assert response_dict['success'] is True
    except HTTPError as error:
        print("{}: {}".format(dict_dataset["name"], error.read()))



    dict_res = {}
    dict_res['id'] = str(uuid.uuid3(uuid.NAMESPACE_DNS, row['url']))
    dict_res['package_id'] = re.sub(r'\W', '-', row['resource']).lower()
    dict_res['url'] = row['url']
    dict_res['title'] = row['resource']
    dict_res['name'] = row['resource']

    request_res = Request('http://%s/api/action/resource_create' % ckan_host)
    request_res.add_header('Authorization', ckan_api_key)
    data_string = quote(json.dumps(dict_res)).encode('utf8')
    try:
        response = urlopen(request_res, data_string)
        # Use the json module to load CKAN's response into a dictionary.
        response_dict = json.loads(response.read().decode())
        assert response_dict['success'] is True
    except HTTPError as error:
        print("{}: {}".format(dict_res['description'], error.read()))
