ckan_fr_organizations = ["Premier ministre",
    "Eurostat",
    "Institut National de la Statistique et des Etudes Economiques (INSEE)",
    "OpenStreetMap",
    "Institut National de l'Information Géographique et Forestière",
    "DataFrance",
    "Ministère des Affaires sociales, de la Santé et des Droits des femmes",
    "Data Publica",
    "Caisse nationale de l'assurance maladie des travailleurs salariés",
    "Région Île-de-France",
    "Enseignement supérieur et Recherche",
    "La Poste",
    "Etalab",
    "Mairie de Paris",
    "Ministère de l'Ecologie du Développement Durable et de l'Energie",
    "Ministère de l'Agriculture, de l'Agroalimentaire et de la Forêt",
    "Ministère de l'Economie, de l'Industrie et du Numérique",
    "Ministère de la ville, de la jeunesse et des sports",
    "Ville de Saint-Malo",
    "Ministère du travail, de l'emploi et du dialogue social",
    "Mairie de Monacia d'Aullène",
    "NosDonnées.fr",
    "Banque Mondiale",
    "data.gouv.fr",
    "Open Food Facts",
    "IRDES & ECOSANTE.FR : Institut de Recherche et Documentation en Economie de la Santé",
    "Société du Grand Paris",
    "OpenDataSoft",
    "CELTIPHARM",
    "Haute Autorité de santé (HAS)",
    "Agence de services et de paiement (ASP)",
    "Métropole de Lyon",
    "SHOM (opérateur public pour l'information géographique maritime et littorale)",
    "Grand Poitiers Open Data",
    "Office national de l'eau et des milieux aquatiques (ONEMA)",
    "Ville d'Issy-les-Moulineaux ***",
    "Open PACA",
    "Commune de Brocas **",
    "Cour des comptes",
    "CNIL",
    "ADEME",
    "Météo-France",
    "Pôle emploi",
    "Agence Technique de l'information sur l'Hospitalisation (ATIH)",
    "Agence Bio",
    "Rennes Métropole",
    "Région Provence-Alpes-Côte d'Azur",
    "Grand Paris Seine Ouest",
    "Agence nationale des fréquences",
    "IdeesLibres.org (Base de données des accidents corporels de la circulation)",
    "Ministère de l'Egalité des Territoires et du Logement",
    "Institut national de l'origine et de la qualité (INAO)",
    "Ined",
    "Emc3 / Géoclip ***",
    "Ville de Montpellier",
    "Agence nationale de sécurité sanitaire, de l'alimentation, de l'environnement et du travail (ANSES)",
    "Ville de Rennes",
    "Autorité de régulation des communications électroniques et des postes (ARCEP)",
    "METZ METROPOLE",
    "IAU-ÎdF (Institut d'Aménagement et d'Urbanisme)",
    "Agence Nationale de Sécurité du Médicament et des produits de santé (ANSM)",
    "Nantes Métropole",
    "Fédération Asso1901",
    "Pôle Réseaux de Chaleur - Cerema",
    "Rennes Métropole en accès libre",
    "Département de Loire-Atlantique",
    "Sénat",
    "Office National des Forêts",
    "Conseil général de Saône-et-Loire (CG71)",
    "ACTION Nogent-sur-Marne ***",
    "Ville de Nantes",
    "Ressourcerie datalocale (Portail mutualisé de données publiques locales pour le territoire de l'aquitaine)",
    "Conseil Régional Nord-Pas de Calais",
    "Mairie de Toulouse",
    "Commune de Chaville",
    "Agence Nationale pour l'Amélioration des Conditions de Travail (ANACT)",
    "Agence nationale pour la cohésion sociale et l'égalité des chances",
    "Direction Départementale des Territoires du Haut-Rhin (68)",
    "Hauts-de-Seine le Département",
    "Conseil général de l'Oise",
    "FranceAgriMer - Établissement national des produits de l'agriculture et de la mer",
    "Toulouse métrople",
    "Région des Pays de la Loire",
    "Communauté urbaine de Bordeaux",
    "Conseil général de la Manche",
    "Commune de Ville d'Avray",
    "PSE - Ecole d'Economie de Paris (base de données des plus haut revenus)",
    "Conseil général de la Gironde",
    "Système d'Information sur l'Eau",
    "Ville de Marseille",
    "GéoBourgogne",
    "Saint Quentin (Aisne)",
    "Coulommiers",
    "Région Alsace",
    "Agence nationale pour la rénovation urbaine",
    "Ville de Vanves",
    "Open Météo Foundation",
    "Inria",
    "Croix-Rouge française",
    "Agence Nationale d'Appui à la Performance des établissements de santé et médico-sociaux (ANAP)",
    "Toulouse-Métropole.data",
    "GEORHONEALPES",
    "Conseil général de Loir-et-Cher ",
    "Bouches-du-Rhône Tourisme",
    "Ville de Digne-les-Bains",
    "Direction Départementale des Territoires et de la Mer de la Somme",
    "Ville de Boulogne-Billancourt",
    "Ville de Sèvres",
    "Portail mutualisé Nantes / Loire-Atlantique / Pays de la Loire",
    "Longjumeau",
    "CeNGEPS (Centre National de Gestion des Essais de Produits de Santé)",
    "Observatoire français des drogues et des toxicomanies",
    "WWF",
    "Veille sur la cigarette électronique - Absolut Vapor ",
    "Caisse nationale de solidarité pour l'autonomie",
    "Agence Nationale pour l'Information sur le Logement (ANIL)",
    "Collectivité Territoriale de Corse",
    "Direction Départementale des Territoires de l'Aube",
    "OpenData Oise",
    "Région Basse-Normandie",
    "Marseille Provence Métropole",
    "Métropole Nice Côte d'Azur",
    "Les Lilas",
    "Conseil Général du Cantal",
    "Altercarto",
    "Université participative",
    "Ville d'Aix-en-Provence",
    "Conseil régional d'Aquitaine",
    "Haute Autorité pour la transparence de la vie publique",
    "Kel Quartier",
    "Institut de radioprotection et de sûreté nucléaire (IRSN)",
    "Conseil général de l'Essonne",
    "Centre Régional Information Jeunesse Poitou-Charentes",
    "Saint-Lô (Manche)",
    "Open Knowledge Foundation France",
    "Communauté d'agglomération Caen la mer",
    "Montpellier Territoire Numérique",
    "Direction Régionale de l'Environnement, de l'Aménagement et du Logement de l'Aquitaine",
    "Open Data 71",
    "Direction Départementale des Territoires de l'Ariège",
    "Angers Loire Métropole",
    "Open Data Nord-Pas de Calais",
    "Pas-de-Calais tourisme",
    "Var Tourisme",
    "Villemomble",
    "Airaq",
    "Direction Départementale des Territoires et de la Mer des Pyrénées-Atlantiques",
    "JCDecaux developer",
    "Irstea",
    "Pays d'Aubagne et de l'Etoile",
    "Agence d'Urbanisme de Rouen et des Boucles de Seine et Eure",
    "Ville de Meudon",
    "Mission Très Haut Débit",
    "Un sur Quatre",
    "Conseil Constitutionnel",
    "Ville de Besancon",
    "CNR",
    "Easter-eggs",
    "Conseil général des Landes",
    "Direction Départementale des Territoires du Gers",
    "Comité Départemental du Tourisme",
    "Open Data Alsace",
    "Loire-Atlantique Développement",
    "Communauté d'Agglomération du Pays Ajaccien",
    "Direction Départementale des Territoires de Saône-et-Loire",
    "ADT et OTs des Alpes-de-Haute-Provence",
    "Communauté du Pays d'Aix",
    "Arles Crau Camargue Montagnette",
    "GIP Corse Compétences",
    "DIRECTION DEPARTEMENTALE DES TERRITOIRES DE SAONE-ET-LOIRE (71)",
    "Mairie de Louviers",
    "Communauté d'Agglomération Plaine Centrale du Val-de-Marne",
    "Service d'Information du Gouvernement",
    "Cap Retraite",
    "École nationale supérieure des métiers de l'image et du son (La Fémis)",
    "Open Data Bourgogne",
    "META Information Technology",
    "Agence de l'eau Adour-Garonne",
    "Agence Française de Développement (AFD)",
    "Agence de l'eau Loire-Bretagne",
    "Réseau de Transport d'Electricité",
    "Saint-Maur des Fossés",
    "Banque de France",
    "Agence NTIC Bourgogne",
    "Communauté urbaine de Bordeaux",
    "Direction Départementale des Territoires de l'Essonne",
    "Direction Régionale de l'Environnement, de l'Aménagement et du Logement de Franche-Comté",
    "Systèmes d’Informations géographiques en Languedoc-Roussillon",
    "Direction Régionale de l'Environnement, de l'Aménagement et du Logement Poitou-Charentes",
    "Direction Départementale des Territoires de la Marne",
    "Institut français de recherche pour l'exploitation de la mer (IFREMER)",
    "Direction Départementale des Territoires de Lot-et-Garonne",
    "Géocatalogue",
    "Agence de l'eau Rhône-Méditerranée et Corse",
    "Sarlat-La Canéda",
    "Air Pays de la Loire",
    "Ville de Marnes-la-Coquette",
    "Plateforme Publique de l'Information Géographique Nord Pas de Calais",
    "Direction Départementale des Territoires et de la Mer des Bouches-du-Rhône",
    "Direction Départementale des Territoires de Seine-et-Marne",
    "Agence des espaces verts - IDF",
    "Centre National des Œuvres Universitaires et Scolaires",
    "Région Provence-Alpes-Côte d'Azur - MV2",
    "SAINT-MALO AGGLOMERATION",
    "Mairie de Créteil",
    "Brest métropole",
    "Le Perreux sur Marne",
    "Ville de Nogent-sur-Marne",
    "Le Télégramme",
    "La Cryobanque Nationale",
    "Archipel Molène",
    "Syndicat mixte du Pays d'Arles",
    "Fédération Nationale des Bistrots de Pays",
    "Syndicat Mixte des Transports des Bouches-du-Rhône",
    "Région Provence-Alpes-Côte d'Azur - Earthcase",
    "Aquitaine Europe Communication",
    "Open Data France",
    "Gironde numérique",
    "Direction Régionale de l'Environnement, de l'Aménagement et du Logement du Languedoc-Roussillon",
    "Direction Départementale des Territoires de l'Orne",
    "Pays de Morlaix",
    "Mairie de Bouloc",
    "Communauté d agglomération de Saint  Quentin en Yvelines",
    "Agence SEO Vip-agence.com",
    "Préfecture de la Lozère",
    "Centre national de la fonction publique territoriale ",
    "Union Nationale des Associations Familiales",
    "Département des Côtes d'Armor",
    "Direction Départementale des Territoires et de la Mer des Landes",
    "Direction Régionale de l'Environnement, de l'Aménagement et du Logement de Bretagne",
    "Direction Départementale des Territoires des Vosges",
    "Direction Départementale des Territoires d'Eure-et-Loir",
    "Direction Départementale des Territoires du Loiret",
    "Direction Régionale de L'Environnement, de l'Aménagement et du Logement de l'Auvergne",
    "Direction Départementale des Territoires de Loir-et-Cher",
    "Direction Départementale des Territoires d'Indre-et-Loire",
    "Direction Départementale des Territoires et de la Mer du Calvados",
    "Direction Départementale des Territoires et de la Mer de Charente-Maritime",
    "Direction Départementale et des Territoires du Cantal",
    "Direction Départementale des Territoires des Alpes de Haute-Provence",
    "Région Bretagne",
    "Direction Départementale des Territoires de Charente",
    "Direction Départementale des Territoires de la Corrèze",
    "Direction Départementale des Territoires du Val d'Oise",
    "Direction Régionale de l'Environnement, de l'Aménagement et du Logement du Nord-Pas-de-Calais",
    "Direction Départementale des Territoires du Doubs",
    "Direction Départementale des Territoires de la Lozère",
    "Direction Départementale des Territoires de Meurthe-et-Moselle",
    "Direction Régionale de l'Environnement de l'Aménagement et du Logement de Lorraine",
    "Centre Régional Auvergnat de l'Information Géographique",
    "Ville de Digne-les-Bains - CCAS",
    "Direction Régionale et Interdépartementale de l'Équipement et de l'Aménagement d'Île-de-France",
    "Observatoire socio-économique du Ventoux",
    "SAN Ouest Provence",
    "Direction Départementale des Territoires de Haute-Saône",
    "Service départemental d'incendie et de secours du Tarn",
    "AirPACA",
    "CRIGE-PACA",
    "Ville de Mahina",
    "Ville de Limoges",
    "Chambre de Métiers et de l'Artisanat de Tarn-et-Garonne",
    "Région des Pays de la Loire ouverture des données publiques",
    "AIR LR",
    "Pôle métier Eau & Environnement CRIGE-PACA",
    "Direction Départementale des Territoires et de la Mer du Var",
    "Association Breizh Small Business Act",
    "Ville d'Arles - Commune de Saint-Martin-de-Crau -ACCM",
    "Chambre de Commerce et d'Industrie Marseille Provence",
    "CCI Territoire de Montpellier",
    "Bassin Adour garonne",
    "Commune de Saint-André-de-Cubzac",
    "Service central d’hydrométéorologie et d’appui à la prévision des inondations",
    "Autolib' Métropole",
    "Marseille-Provence 2013",
    "Fédération des laboureurs en herbe",
    "Coopération pour l’Information Géographique en Alsace (CIGAL)",
    "Syndicat Départemental des Energies de Seine-et-Marne",
    "Direction Départementale des Territoires de la Sarthe",
    "Village de Peipin",
    "Région Provence-Alpes-Côte d'Azur - ITEMS",
    "Montpellier Bac à Sable",
    "Polytech'Tours",
    "réseau Sentinelles",
    "Ville d'Istres",
    "Ordre des Géomètres-Experts",
    "Association Trans Musicales",
    "OpenBikes",
    "Université Paris-Est Marne-La-Vallée",
    "Observatoire Régional de l'Environnement Poitou-Charentes",
    "Morbihan énergies",
    "Direction Départementale des Territoires du Bas-Rhin",
    "Parc naturel régional du Marais poitevin",
    "Communauté d'Agglomération Terres de France",
    "Open Météo Foundation",
    "CHU Nîmes",
    "Participants OpenDataCamp",
    "Association Infoclimat",
    "Mairie de Balma",
    "COMMUNE DE BOUILLAC",
    "Gironde numérique",
    "Conseil général de la Gironde",
    "Mairie de Menton",
    "Communauté Urbaine d'Arras",
    "Région Lorraine",
    "Direction Départementale des Territoires de l'Isère",
    "Mairie de Seilh",
    "Lorient Agglomération",
    "Direction Régionale de l'Environnement, de l'Aménagement et du Logement du Centre-Val de Loire",
    "Allocations familiales ",
    "Université du Temps Libre en Libournais",
    "Picardie Nature",
    "Ressourcerie datalocale",
    "Bassin Adour garonne",
    "Conseil régional d'Aquitaine",
    "Commune de Saint-André-de-Cubzac"]
